import Link from "next/link";

export const metadata = {
  title: "Terms of Service & Content Policy — Atelier",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-12 md:px-12">
      <div className="max-w-2xl mx-auto">
        <p className="text-sm text-parchment/60 mb-2">
          <Link href="/" className="hover:text-gold">
            ← Atelier
          </Link>
        </p>
        <h1 className="font-display text-3xl mb-2">Terms of Service &amp; Content Policy</h1>
        <p className="text-sm text-parchment/50 mb-10">Last updated: July 2026</p>

        <div className="space-y-8 text-sm leading-relaxed text-parchment/80">
          <section>
            <h2 className="font-display text-xl text-parchment mb-2">1. Who can use Atelier</h2>
            <p>
              Atelier is for adults. You must be at least 18 years old to create an account. By registering you
              confirm your date of birth is accurate and that you meet this requirement. We rely on this
              confirmation — you agree not to misrepresent your age, and not to help anyone under 18 access the
              service, including by sharing your account or generated content with them.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-parchment mb-2">2. What Atelier is</h2>
            <p>
              Atelier lets you create fictional AI characters and have conversations with them. Character replies
              are generated by third-party language models; they are not real people, do not reflect Atelier's or
              any provider's views, and should not be relied on for factual, medical, legal, or financial
              decisions.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-parchment mb-2">3. Mature content</h2>
            <p>
              Some characters and conversations on Atelier may include mature or explicit fictional content
              ("explicit mode"). This content is generated for your private use and is never included in the
              public Discover gallery. By using explicit mode you confirm you're an adult in your jurisdiction and
              that viewing such content is legal where you live.
            </p>
            <p className="mt-3">Regardless of mode, you may not use Atelier to create, request, or share content that:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>depicts, describes, or sexualizes anyone under 18, including fictional characters framed or described as minors;</li>
              <li>depicts non-consensual sexual content presented approvingly, or content intended to facilitate real-world sexual exploitation, harassment, or stalking of a real person;</li>
              <li>impersonates a real, identifiable person without their consent, especially in sexual or defamatory contexts;</li>
              <li>promotes hate, violent extremism, or discrimination against a protected group;</li>
              <li>provides instructions for weapons, illegal drugs, or other content intended to cause serious harm.</li>
            </ul>
            <p className="mt-3">
              Accounts used to generate or share this kind of content will be suspended or terminated, and we may
              report unlawful content, including anything involving the sexual exploitation of minors, to relevant
              authorities.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-parchment mb-2">4. Sharing to Discover</h2>
            <p>
              Discover is a public gallery of characters other users choose to share. Explicit characters can never
              be shared publicly — that restriction is enforced by the app itself, not just this policy. Anything
              you mark public is visible to every Atelier user and can be reported. We may remove shared characters,
              or suspend the ability to share, at our discretion, including in response to reports under Section 5.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-parchment mb-2">5. Reporting &amp; moderation</h2>
            <p>
              If you see a shared character that violates this policy, use the Report button on its card in
              Discover. Reports are reviewed by Atelier; a character can be automatically hidden from Discover while
              a report is pending review. We may dismiss a report, keep a character hidden, or remove it entirely.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-parchment mb-2">6. Your account</h2>
            <p>
              You're responsible for the security of your account and password. Tell us right away if you believe
              your account has been compromised. We may suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-parchment mb-2">7. No warranty; limitation of liability</h2>
            <p>
              Atelier is provided "as is," without warranties of any kind. AI-generated content can be inaccurate,
              offensive, or otherwise objectionable despite our efforts to prevent that. To the fullest extent
              permitted by law, Atelier and its operators aren't liable for damages arising from your use of the
              service or its generated content.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-parchment mb-2">8. Changes</h2>
            <p>
              We may update these terms as the product changes. Material changes will be reflected by the "last
              updated" date above; continued use after a change means you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl text-parchment mb-2">9. Contact</h2>
            <p>
              Questions, reports, or removal requests: reach us via the contact details on our site. See also our{" "}
              <Link href="/privacy" className="text-gold hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
